### ISSUE TITLE
Media queries and styled

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#63]
The following style
```js
import { Link } from '@dark-engine/web-router'
import { styled, css } from '@dark-engine/styled'

const disabledStyle = ({ disabled }) => {
  if (disabled) {
    return css`
    pointer-events: none;
    opacity: .2;`
  }
  return css`
  pointer-events: auto;
  opacity: 1;`
}

const underlineStyle = ({ underline }) => {
  if (underline) {
    return css`text-decoration: none;
    background-image: linear-gradient(currentColor,currentColor);
    background-repeat: no-repeat;
    transition: background-size .3s;`
  }
}

const activeStyle = ({ active }) => {
  if (active) {
    return css`
    background-position: 0 100%;
    background-size: 100% 1px;
    @media(hover: hover) {
      &:hover {
        background-position:100% 100%;
        background-size: 0 1px
      }
    }

    @media(hover: none) {
      &:active {
        background-position:100% 100%;
        background-size: 0 1px
      }
    }`
  }

  return css`
  background-position: 100% 100%;
  background-size: 0 1px;
  @media(hover: hover) {
    &:hover {
        background-position:0 100%;
        background-size: 100% 1px;
    }
  }

  @media(hover: none) {
    &:active {
        background-position:0 100%;
        background-size: 100% 1px;
    }
  }`
}

export const button = ({ disabled, underline, active }) => css`
  position: relative;
  display: inline-flex;
  align-items: center;

  ${disabledStyle({ disabled })}
  ${underlineStyle({ underline })}
  ${activeStyle({ active })}`

const StyledLink = styled(Link)`
  ${({ disabled, active }) => button({ disabled, underline: true, active })}
`
```

Results into this in the browser
```css
.dk-jeihhc {
  position: relative;
  display: inline-flex;
  align-items: center;
  pointer-events: auto;
  opacity: 1;
  text-decoration: none;
  background-image: linear-gradient(currentColor, currentColor);
  background-repeat: no-repeat;
  transition: background-size .3s;
  background-position: 100% 100%;
  background-size: 0 1px;
}

@media(hover: hover) {
  .dk-jeihhc {}

  .null:hover {
    background-position: 0 100%;
    background-size: 100% 1px;
  }
}

@media(hover: none) {
  .dk-jeihhc {}

  .null:active {
    background-position: 0 100%;
    background-size: 100% 1px;
  }
}

.dk-jeihhc {
  position: relative;
  display: inline-flex;
  align-items: center;
  pointer-events: auto;
  opacity: 1;
  text-decoration: none;
  background-image: linear-gradient(currentColor, currentColor);
  background-repeat: no-repeat;
  transition: background-size .3s;
  background-position: 100% 100%;
  background-size: 0 1px;
}

@media(hover: hover) {
  .dk-jeihhc {}

  .null:hover {
    background-position: 0 100%;
    background-size: 100% 1px;
  }
}

@media(hover: none) {
  .dk-jeihhc {}

  .null:active {
    background-position: 0 100%;
    background-size: 100% 1px;
  }
}
```

I see a few weird things happening, but most importantly, the media queries are broken. `&:hover` becomes `.null:hover`
Am I doing it wrong?

**Comment by atellmer** [comment]
You are inserting a call to one CSS function into another, this is not supported. At least it never occurred to me why this would be necessary. Your approach is very different from styled-components. You wrap everything in one dynamic function, which means that the styles will be duplicated in the style tag. Try to separate static styles from dynamic ones.
Try it:

```tsx
const disabledStyle = ({ disabled }) => {
  if (disabled) {
    return css`
      pointer-events: none;
      opacity: 0.2;
    `;
  }

  return css`
    pointer-events: auto;
    opacity: 1;
  `;
};

const underlineStyle = ({ underline }) => {
  if (underline) {
    return css`
      text-decoration: none;
      background-image: linear-gradient(currentColor, currentColor);
      background-repeat: no-repeat;
      transition: background-size 0.3s;
    `;
  }

  return '';
};

const activeStyle = ({ active }) => {
  if (active) {
    return css`
      background-position: 0 100%;
      background-size: 100% 1px;

      @media (hover: hover) {
        &:hover {
          background-position: 100% 100%;
          background-size: 0 1px;
        }
      }

      @media (hover: none) {
        &:active {
          background-position: 100% 100%;
          background-size: 0 1px;
        }
      }
    `;
  }

  return css`
    background-position: 100% 100%;
    background-size: 0 1px;

    @media (hover: hover) {
      &:hover {
        background-position: 0 100%;
        background-size: 100% 1px;
      }
    }

    @media (hover: none) {
      &:active {
        background-position: 0 100%;
        background-size: 100% 1px;
      }
    }
  `;
};

const StyledLink = styled(Link)`
  // first (static) class .dk-behaba
  position: relative;
  display: inline-flex;
  align-items: center;
  ${underlineStyle({ underline: true })}

  // second (dynamic) class .dk-badcfa
  ${({ disabled }) => disabledStyle({ disabled })}

  // third (dynamic) class .dk-hdbbge
  ${({ active }) => activeStyle({ active })}
`;
```

```css
<style>
    .dk-behaba {
      position: relative;
      display: inline-flex;
      align-items: center;
      text-decoration: none;
      background-image: linear-gradient(currentColor, currentColor);
      background-repeat: no-repeat;
      transition: background-size 0.3s;
    }

    .dk-badcfa {
      pointer-events: auto;
      opacity: 1;
    }

    .dk-hdbbge {
      background-position: 100% 100%;
      background-size: 0 1px;
    }

    @media (hover: hover) {
      .dk-hdbbge {}

      .dk-hdbbge:hover {
        background-position: 0 100%;
        background-size: 100% 1px;
      }
    }

    @media (hover: none) {
      .dk-hdbbge {}

      .dk-hdbbge:active {
        background-position: 0 100%;
        background-size: 100% 1px;
      }
    }

    .dk-bbgjch {
      background-position: 0 100%;
      background-size: 100% 1px;
    }

    @media (hover: hover) {
      .dk-bbgjch {}

      .dk-bbgjch:hover {
        background-position: 100% 100%;
        background-size: 0 1px;
      }
    }

    @media (hover: none) {
      .dk-bbgjch {}

      .dk-bbgjch:active {
        background-position: 100% 100%;
        background-size: 0 1px;
      }
    }

    .dk-bjfhbc {
      pointer-events: none;
      opacity: 0.2;
    }
  </style>
```
