### ISSUE TITLE
styled bad order

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#72]
```js
const LinksRow = styled.div`
  display: flex;
  justify-content: space-between;
  gap: 2.5vw;
  & ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
    width: 100%;
  }
  & ul li {
    list-style: none;
    border-bottom: ${props => props.theme.borderStyle};
  }
  & ul li a {
    display: flex;
    justify-content: space-between;
    align-items: center;
    text-decoration: none;
    color: ${props => props.theme.black};
    padding: .5vw 0;
    transition: color .2s, background-color .2s, padding .3s;
  }
  & ul li a:hover {
    color: ${props => props.theme.white};
    background-color: ${props => props.theme.black};
    padding: .5vw;
  }
  @media (prefers-reduced-motion: reduce) {
    & ul li a {
      transition: none;
    }
  }
`
```

the media query style is outputted before the `& ul li a` style.
```css
@media (prefers-reduced-motion: reduce) {
  .dk-cadhch {}

  .dk-cadhch ul li a {
    transition: none;
  }
}

.dk-bfhafa {}

.dk-bfhafa ul li {
  list-style: none;
  border-bottom: solid 1px #1e1f1f;
}

.dk-bdfidj {}

.dk-bdfidj ul li a {
  display: flex;
  justify-content: space-between;
  align-items: center;
  text-decoration: none;
  color: #1e1f1f;
  padding: .5vw 0;
  transition: color .2s, background-color .2s, padding .3s;
}
```
Because they have the same specificity, the browser ignores the media query styles. I believe the media query should be put after the styles defined before it.

**Comment by atellmer** [comment]
As far as I remember, media-rules are added to the end, but depending on whether the style is static or dynamic. The order is: static style + static media + dynamic style + dynamic media.

Try workaround:

```css
@media (prefers-reduced-motion: reduce) {
    & ul li a {
      transition: ${() => 'none'}; // fn
    }
 }
```

**Comment by Coachonko** [comment]
> Try workaround:
> 
> ```css
> @media (prefers-reduced-motion: reduce) {
>     & ul li a {
>       transition: ${() => 'none'}; // fn
>     }
>  }
> ```

The order is unchanged. Besides, I do not think it is a good solution: I really have to think about the way styled works to sort my attributes based on that. I think I defined the media query at the end and it should be rendered at the end, according to the order I defined it.

**Comment by atellmer** [comment]
Let's say we have this code and media-query is inserted at the end when mounting the component. Everything will work. But what happens when a new component with a different color appears? The style will be calculated and inserted at the end of the style tag and it will no longer be correct. What to do in this case, provided that we cannot touch already inserted styles. Otherwise, we would have to parse the already inserted style blocks from the entire application every time: something has changed and we parse the entire style tag again, rearrange the styles and rewrite the tag again. This looks like a second parsing job and it will most likely be slow. What to do in this case?

```tsx
const Box = styled.div`
  & a {
    color: ${props => props.$color};
  }

  @media (max-width: 800px) {
    & a {
      color: red;
    }
  }
`;
```

**Comment by Coachonko** [comment]
Shouldn't styled create a new class for the different color and insert it afterwards?
```js
const Box = styled.div`
  & a {
    color: ${props => props.$color};
  }

  @media (max-width: 800px) {
    & a {
      color: red;
    }
  }
`;
```
```css
.class-one a {
  color: blue;
}
@media (max-width: 800px) {
  .class-one a {
    color: red;
  }
}

.class-two a {
  color: green;
}
@media (max-width: 800px) {
  .class-two a {
    color: red;
  }
}
```

**Comment by atellmer** [comment]
Then we need to support one more nesting, because `&` in your example refers to different class names: the first refers to a dynamic class, and the second to a static one.

I don't know how easy it is to add this to the current architecture. We need to see if this can be done in the original styled-components.

```tsx
const Box = styled.div`
  & a {
    color: ${props => props.$color};

    @media (max-width: 800px) {
       color: red;
    }
  }
`;
```

**Comment by Coachonko** [comment]
Outdated react and styled component versions because I just cloned the first random github repository to test this

```
const Box = styled.div`
  & a {
    font-weight: bold;
    color: ${props => `${props.$color}`};
  }

  @media (max-width: 800px) {
    & a {
      color: red;
    }
  }
`;

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      name: 'React',
    };
  }

  render() {
    const items = Array.from(Array(99).keys());
    return (<>
      <Box $color='blue'>
        <a>blue</a>
      </Box>
      <Box $color='green'>
        <a>green</a>
      </Box>
      </>
    );
  }
}
```
```
<style data-styled="active" data-styled-version="5.3.3">
.gLrqxF a{font-weight:bold;color:blue;}@media (max-width:800px){.gLrqxF a{color:red;}}
.eKiNWE a{font-weight:bold;color:green;}@media (max-width:800px){.eKiNWE a{color:red;}}
</style>
```

**Comment by atellmer** [comment]
If we change the code a little, we will see this in styled-components

```tsx
const Box = styled.div`
  background-color: blue;
  color: black;

  & a {
    font-weight: bold;
    color: ${(props) => `${props.$color}`};
  }

  @media (max-width: 800px) {
    & a {
      color: red;
    }
  }
`;
```

```css
.iLKKBR {
  background-color: blue;
  color: black;
}

.iLKKBR a {
  font-weight: bold;
  color: blue;
}

@media (max-width: 800px) {
  .iLKKBR a {
    color: red;
  }
}

.duYaUQ {
  background-color: blue;
  color: black;
}

.duYaUQ a {
  font-weight: bold;
  color: green;
}

@media (max-width: 800px) {
  .duYaUQ a {
    color: red;
  }
}
```

It looks like it just stupidly duplicates all the styles for the new props. I had a better opinion of them. This just generates a bunch of duplicate code. And the css of the component can be quite large, apparently it will repeat all this.

Dark generates this (without empty classes, i will fix it later)

```css
.dk-caccjf {
  background-color: blue;
  color: black;
}

@media (max-width: 800px) {
  .dk-caccjf a {
    color: red !important; // for now
  }
}

.dk-dbegje a {
  font-weight: bold;
  color: blue;
}

.dk-iaijad a {
  font-weight: bold;
  color: green;
}
```

Anyway, I will think about it.

**Comment by Coachonko** [comment]
> It looks like it just stupidly duplicates all the styles for the new props. I had a better opinion of them. This just generates a bunch of duplicate code. And the css of the component can be quite large, apparently it will repeat all this.

You're right, in styled-components 5.3.3
```js
const Box = styled.div`
  background-color: lightgray;
  color: black;
  & a {
    font-weight: bold;
    color: ${props => `${props.$color}`};
    @media (max-width: 800px) {
      color: red;
  }
`;

class App extends Component {
  render() {
    return (
      <>
      <Box $color='blue'>
        <a>blue</a>
      </Box>
      <Box $color='green'>
        <a>green</a>
      </Box>
      </>
    );
  }
}
```
results in
```css
.biclYi {
  background-color: lightgray;
  color: black;
}

.biclYi a {
  font-weight: bold;
  color: blue;
}

@media (max-width:800px) {
  .biclYi a {
    color: red;
  }
}

.bLMHlz {
  background-color: lightgray;
  color: black;
}

.bLMHlz a {
  font-weight: bold;
  color: green;
}

@media (max-width:800px) {
  .bLMHlz a {
    color: red;
  }
}
```
`bLMHlz` is a duplicate of `biclYi`. 
That is wasteful, although I believe it may not be as bad when utilizing gzip. React is also quite a large piece of code compared to Dark. 
On what version did you test this?

**Comment by atellmer** [comment]
> On what version did you test this?

```json
"dependencies": {
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "styled-components": "6.1.11"
  },
```

gzip can certainly help, but we stand for beautiful solutions, and repeating styles that do not require repetition is not beautiful.

**Comment by Coachonko** [comment]
>     color: red !important; // for now
I've been trained to be afraid of `!important`, I don't have much experience with that. Wouldn't it cause problem with multiple media queries?
```
const Box = styled.div`
  & a {
    font-weight: bold;
    color: ${props => `${props.$color}`};
  }

  @media (max-width: 500px) {
    & a {
      color: red;
    }
    
  @media (max-width: 900px) {
    & a {
      color: teal;
    }
  }
`;
```

> gzip can certainly help, but we stand for beautiful solutions, and repeating styles that do not require repetition is not beautiful.

I absolutely agree, as long as it works

**Comment by atellmer** [comment]
`!important` can be useful, but in this case you can use some special attribute that can be attached to the tag. For example, `data-spec` or some other name. This is again like a workaround.

```css
@media (min-width: 500px) {
  & a[data-spec] {
    color: red;
  }
}
```

In this case, these expressions will be added in the order they are written, so here you set the priority yourself.
```css
@media (min-width: 500px) {
  & a {
    color: red;
  }
}

@media (min-width: 900px) {
  & a {
    color: teal;
  }
}
```

**Comment by atellmer** [comment]
> Update: I thought about this a bit more and I do think it is also important for the API to not be complex. I personally want to just write something as close as the CSS I would have written in a CSS module when using styled, any extra complexity is going to make me want to use another solution. There already is enough complexity, too much in this field, to add more.

Based on this logic, in your case it would be ideal to use CSS variables rather than generate styles dynamically. This would remove this problem and work faster because there is no js calculations there. At the same time, the theme could also be switched, simply changing the variables in `<GlobalStyle />`, for example `--black`, `--borderStyle` and others.

**Comment by Coachonko** [comment]
> Based on this logic, in your case it would be ideal to use CSS variables rather than generate styles dynamically. This would remove this problem and work faster because there is no js calculations. At the same time, the theme could also be switched, simply changing the variables in `<GlobalStyle />`, for example `--black`, `--borderStyle` and others.

I do that already, but the original issue was about the wrong position of media queries generated with
```
  @media (prefers-reduced-motion: reduce) {
    & ul li a {
      transition: none;
    }
  }
```
In this situation I guess `!important` can work, but I wouldn't have reached for an `!important` here.

Again, I do not want to think in which situation I should use one technique and in which situation I should use another. Maintaining such a codebase would be awful: some media queries here some there, some use weird selectors some don't.
If the solution does not generate optimal code but it leads to less headaches, it may just be the better solution to the problem. Maybe in the future a better solution can be found.

**Comment by atellmer** [comment]
These solutions have been proposed as hacks until I can make fixes to the codebase. But I also have to say that I won't be able to contribute them as often as I'd like, because open-source is not where I work.

**Comment by Coachonko** [comment]
> These solutions have been proposed as hacks until I can make fixes to the codebase. But I also have to say that I won't be able to contribute them as often as I'd like, because open-source is not where I work.

Of course.
I think there was a misunderstanding, I had the impression that this issue was not being acknowledged as an issue.
I apologize if I came across as demanding.

**Comment by atellmer** [comment]
In the new version this code will generate these styles

```tsx
const Box = styled.div`
  background-color: pink;
  color: black;

  & a {
    font-weight: bold;
    color: ${p => `${p.$color}`};

    @media (max-width: 800px) {
      color: red;
    }
  }
`;

createRoot(document.getElementById('root')).render(
  <>
    <Box $color='blue'>
      <a>blue</a>
    </Box>
    <Box $color='green'>
      <a>green</a>
    </Box>
  </>,
);
```

```css
.dk-bjjdjh {
  background-color: pink;
  color: black;
}

.dk-ggedee a {
  font-weight: bold;
  color: blue;
}

@media (max-width: 800px) {
  .dk-ggedee a {
    color: red;
  }
}

.dk-bjajid a {
  font-weight: bold;
  color: green;
}

@media (max-width: 800px) {
  .dk-bjajid a {
    color: red;
  }
}
```
